In [1]:
import numpy as np
attack_rates = np.array([80,75,90,85])

print(attack_rates)

[80 75 90 85]

In [2]:
print(np.mean(attack_rates))

82.5

In [3]:
print(np.max(attack_rates))

90

In [4]:
print(np.max(attack_rates))

90

In [5]:
import pandas as pd

In [6]:
data = {
    "Attack":["Patch A","Patch B","Patch C"],
    "Success Rate":[80,70,95]
}

df = pd.DataFrame(data)

df

    Attack  Success Rate
0  Patch A            80
1  Patch B            70
2  Patch C            95

In [7]:
df["Success Rate"].mean()
df.sort_values("Success Rate")

    Attack  Success Rate
1  Patch B            70
0  Patch A            80
2  Patch C            95